name: user_repository
description: The Rep that handlers users
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  collection: ^1.18.0
  firebase_auth: ^5.2.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
