name: rental_car_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  car_repository:
    path: packages/car_repository
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_date_range_picker: ^0.1.1
  flutter_stripe: ^11.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  order_repository:
    path: packages/order_repository
  path_provider: ^2.1.4
  pdf: ^3.11.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  user_repository:
    path: packages/user_repository
  uuid: ^4.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
