name: order_repository
description: The Rep that handlers orders
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
